[package]
name = "rust_web_crawler"
version = "0.1.0"
authors = ["Some-dude-a-long-time-ago <43387168+Some-dude-a-long-time-ago@users.noreply.github.com>"]


[dependencies]
hyper = "0.12.14"
html5ever = "0.22.5"
url = "1.7.2"