[package]
name = "rust_web_crawler"
version = "0.1.0"
authors = ["Some-dude-a-long-time-ago <43387168+Some-dude-a-long-time-ago@users.noreply.github.com>"]


[dependencies]
hyper = "0.10.1"
html5ever = "0.21.0"
url = "0.2.37"