[package]
name = "blockchain"
version = "0.1.0"
authors = ["Some-dude-a-long-time-ago <43387168+Some-dude-a-long-time-ago@users.noreply.github.com>"]

[dependencies]
time = "0.1.4"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.32"
sha2 = "0.8"