[package]
name = "snake"
version = "0.1.0"
authors = ["Some-dude-a-long-time-ago <43387168+Some-dude-a-long-time-ago@users.noreply.github.com>"]

[dependencies]
rand = "0.5.5"
piston_window = "0.82.0"